// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4p3DglfmFHjakXAPsAJ2kiAoyrSHnSE',
    appId: '1:34772031417:web:b8ccfd47f45a8a8c9c8868',
    messagingSenderId: '34772031417',
    projectId: 'resoluteai-b4d22',
    authDomain: 'resoluteai-b4d22.firebaseapp.com',
    storageBucket: 'resoluteai-b4d22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1XTKRguuyKAzwMGcAy59h8GYPuh2cHo',
    appId: '1:34772031417:android:4f141bad8ceb342e9c8868',
    messagingSenderId: '34772031417',
    projectId: 'resoluteai-b4d22',
    storageBucket: 'resoluteai-b4d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Mma72XbmnNLSXw0Bq67mS33HOxSjYqM',
    appId: '1:34772031417:ios:7955a67f1d794e449c8868',
    messagingSenderId: '34772031417',
    projectId: 'resoluteai-b4d22',
    storageBucket: 'resoluteai-b4d22.appspot.com',
    iosBundleId: 'com.example.resoluteai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Mma72XbmnNLSXw0Bq67mS33HOxSjYqM',
    appId: '1:34772031417:ios:7955a67f1d794e449c8868',
    messagingSenderId: '34772031417',
    projectId: 'resoluteai-b4d22',
    storageBucket: 'resoluteai-b4d22.appspot.com',
    iosBundleId: 'com.example.resoluteai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL4p3DglfmFHjakXAPsAJ2kiAoyrSHnSE',
    appId: '1:34772031417:web:6c18881ef6bd6e779c8868',
    messagingSenderId: '34772031417',
    projectId: 'resoluteai-b4d22',
    authDomain: 'resoluteai-b4d22.firebaseapp.com',
    storageBucket: 'resoluteai-b4d22.appspot.com',
  );
}
